/*
 * @Description:
 * @Author: zuoguoliang
 * @Date: 2022-04-27 14:46:59
 * @LastEditors: zuoguoliang
 * @LastEditTime: 2022-04-28 14:43:37
 */

let dataSource = {
  trace: {
    items: [
      {
        container: { id: '4d703afb66113e0d851e89b8829539210e05d935fbfe9dd901a53fec2289f014' },
        process: { pid: 8, title: '/usr/lib/jvm/java-1.8-openjdk/jre/bin/java' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        source: { ip: '10.199.0.13' },
        processor: { name: 'transaction', event: 'transaction' },
        url: {
          path: '/uis/roles/ly-ky-pro-dep/users',
          scheme: 'http',
          port: 1400,
          domain: '192.168.35.217',
          query: 'pageNum=1&pageSize=0&type=1',
          full:
            'http://192.168.35.217:1400/uis/roles/ly-ky-pro-dep/users?pageNum=1&pageSize=0&type=1',
        },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          type: 'apm-server',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.598Z',
        ecs: { version: '1.8.0' },
        service: {
          node: { name: '4d703afb66113e0d851e89b8829539210e05d935fbfe9dd901a53fec2289f014' },
          environment: 'production',
          framework: { name: 'Spring Web MVC', version: '4.3.13.RELEASE' },
          name: 'LY-IACP-SVC',
          runtime: { name: 'Java', version: '1.8.0_242' },
          language: { name: 'Java', version: '1.8.0_242' },
        },
        host: {
          hostname: '4d703afb6611',
          os: { platform: 'Linux' },
          ip: '10.199.0.2',
          name: '4d703afb6611',
          architecture: 'amd64',
        },
        client: { ip: '10.199.0.13' },
        http: {
          request: {
            headers: {
              Connection: ['Keep-Alive'],
              'User-Agent': ['Apache-HttpClient/4.3.3 (java 1.5)'],
              Host: ['192.168.35.217:1400'],
              'Accept-Encoding': ['gzip,deflate'],
            },
            method: 'GET',
            socket: { remote_address: '10.199.0.13' },
          },
          response: {
            headers: {
              'Keep-Alive': ['timeout=60'],
              'Transfer-Encoding': ['chunked'],
              Connection: ['keep-alive'],
              'X-Application-Context': ['ly-iacp-svc:1400'],
              Date: ['Wed, 27 Apr 2022 07:43:24 GMT'],
              'Content-Type': ['application/json;charset=UTF-8'],
            },
            status_code: 200,
            finished: true,
            headers_sent: true,
          },
          version: '1.1',
        },
        event: { ingested: '2022-04-27T07:43:32.636519189Z', outcome: 'success' },
        user_agent: {
          original: 'Apache-HttpClient/4.3.3 (java 1.5)',
          name: 'Apache-HttpClient',
          device: { name: 'Other' },
          version: '4.3.3',
        },
        transaction: {
          duration: { us: 83573 },
          result: 'HTTP 2xx',
          name: 'UserClientController#getAllocationUsersByRoleId',
          span_count: { dropped: 0, started: 15 },
          id: '7a236dfa6fc2509e',
          type: 'request',
          sampled: true,
        },
        timestamp: { us: 1651045404598001 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.630Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        timestamp: { us: 1651045404630219 },
        span: {
          duration: { us: 36576 },
          stacktrace: [
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'DruidPooledPreparedStatement.java',
              classname: 'com.alibaba.druid.pool.DruidPooledPreparedStatement',
              line: { number: 504 },
              module: 'com.alibaba.druid.pool',
              function: 'execute',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'PreparedStatementHandler.java',
              classname: 'org.apache.ibatis.executor.statement.PreparedStatementHandler',
              line: { number: 63 },
              module: 'org.apache.ibatis.executor.statement',
              function: 'query',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'RoutingStatementHandler.java',
              classname: 'org.apache.ibatis.executor.statement.RoutingStatementHandler',
              line: { number: 79 },
              module: 'org.apache.ibatis.executor.statement',
              function: 'query',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'Plugin.java',
              classname: 'org.apache.ibatis.plugin.Plugin',
              line: { number: 63 },
              module: 'org.apache.ibatis.plugin',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'SimpleExecutor.java',
              classname: 'org.apache.ibatis.executor.SimpleExecutor',
              line: { number: 63 },
              function: 'doQuery',
              module: 'org.apache.ibatis.executor',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'BaseExecutor.java',
              classname: 'org.apache.ibatis.executor.BaseExecutor',
              line: { number: 326 },
              module: 'org.apache.ibatis.executor',
              function: 'queryFromDatabase',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'BaseExecutor.java',
              classname: 'org.apache.ibatis.executor.BaseExecutor',
              line: { number: 156 },
              module: 'org.apache.ibatis.executor',
              function: 'query',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'BaseExecutor.java',
              classname: 'org.apache.ibatis.executor.BaseExecutor',
              line: { number: 136 },
              module: 'org.apache.ibatis.executor',
              function: 'query',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'DefaultSqlSession.java',
              classname: 'org.apache.ibatis.session.defaults.DefaultSqlSession',
              line: { number: 148 },
              module: 'org.apache.ibatis.session.defaults',
              function: 'selectList',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'SqlSessionTemplate.java',
              classname: 'org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor',
              line: { number: 433 },
              module: 'org.mybatis.spring',
              function: 'invoke',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'SqlSessionTemplate.java',
              classname: 'org.mybatis.spring.SqlSessionTemplate',
              line: { number: 238 },
              module: 'org.mybatis.spring',
              function: 'selectList',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'MapperMethod.java',
              classname: 'org.apache.ibatis.binding.MapperMethod',
              line: { number: 137 },
              module: 'org.apache.ibatis.binding',
              function: 'executeForMany',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MapperMethod.java',
              classname: 'org.apache.ibatis.binding.MapperMethod',
              line: { number: 76 },
              module: 'org.apache.ibatis.binding',
              function: 'execute',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MapperProxy.java',
              classname: 'org.apache.ibatis.binding.MapperProxy',
              line: { number: 59 },
              function: 'invoke',
              module: 'org.apache.ibatis.binding',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AopUtils.java',
              classname: 'org.springframework.aop.support.AopUtils',
              line: { number: 333 },
              module: 'org.springframework.aop.support',
              function: 'invokeJoinpointUsingReflection',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 190 },
              module: 'org.springframework.aop.framework',
              function: 'invokeJoinpoint',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 157 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'PersistenceExceptionTranslationInterceptor.java',
              classname:
                'org.springframework.dao.support.PersistenceExceptionTranslationInterceptor',
              line: { number: 136 },
              module: 'org.springframework.dao.support',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'JdkDynamicAopProxy.java',
              classname: 'org.springframework.aop.framework.JdkDynamicAopProxy',
              line: { number: 213 },
              module: 'org.springframework.aop.framework',
              function: 'invoke',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: 'UserClientServiceImpl.java',
              classname: 'com.ly.cloud.authc.service.impl.UserClientServiceImpl',
              line: { number: 293 },
              module: 'com.ly.cloud.authc.service.impl',
              function: 'getUsersByRoleId',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: '<generated>',
              classname:
                'com.ly.cloud.authc.service.impl.UserClientServiceImpl$$FastClassBySpringCGLIB$$7e5a448a',
              line: { number: -1 },
              function: 'invoke',
              module: 'com.ly.cloud.authc.service.impl',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MethodProxy.java',
              classname: 'org.springframework.cglib.proxy.MethodProxy',
              line: { number: 204 },
              module: 'org.springframework.cglib.proxy',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'CglibAopProxy.java',
              classname: 'org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation',
              line: { number: 738 },
              module: 'org.springframework.aop.framework',
              function: 'invokeJoinpoint',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 157 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'TransactionInterceptor.java',
              classname: 'org.springframework.transaction.interceptor.TransactionInterceptor$1',
              line: { number: 99 },
              module: 'org.springframework.transaction.interceptor',
              function: 'proceedWithInvocation',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'TransactionAspectSupport.java',
              classname: 'org.springframework.transaction.interceptor.TransactionAspectSupport',
              line: { number: 282 },
              module: 'org.springframework.transaction.interceptor',
              function: 'invokeWithinTransaction',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'TransactionInterceptor.java',
              classname: 'org.springframework.transaction.interceptor.TransactionInterceptor',
              line: { number: 96 },
              function: 'invoke',
              module: 'org.springframework.transaction.interceptor',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'CglibAopProxy.java',
              classname:
                'org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor',
              line: { number: 673 },
              module: 'org.springframework.aop.framework',
              function: 'intercept',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: '<generated>',
              classname:
                'com.ly.cloud.authc.service.impl.UserClientServiceImpl$$EnhancerBySpringCGLIB$$3bb30dca',
              line: { number: -1 },
              function: 'getUsersByRoleId',
              module: 'com.ly.cloud.authc.service.impl',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: 'UserClientController.java',
              classname: 'com.ly.cloud.authc.controller.UserClientController',
              line: { number: 331 },
              module: 'com.ly.cloud.authc.controller',
              function: 'getAllocationUsersByRoleId',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: '<generated>',
              classname:
                'com.ly.cloud.authc.controller.UserClientController$$FastClassBySpringCGLIB$$fc01b8e4',
              line: { number: -1 },
              module: 'com.ly.cloud.authc.controller',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MethodProxy.java',
              classname: 'org.springframework.cglib.proxy.MethodProxy',
              line: { number: 204 },
              module: 'org.springframework.cglib.proxy',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'CglibAopProxy.java',
              classname: 'org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation',
              line: { number: 738 },
              module: 'org.springframework.aop.framework',
              function: 'invokeJoinpoint',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 157 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MethodBeforeAdviceInterceptor.java',
              classname: 'org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor',
              line: { number: 52 },
              module: 'org.springframework.aop.framework.adapter',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              function: 'proceed',
              module: 'org.springframework.aop.framework',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MethodInvocationProceedingJoinPoint.java',
              classname: 'org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint',
              line: { number: 85 },
              module: 'org.springframework.aop.aspectj',
              function: 'proceed',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: 'WebLogAspect.java',
              classname: 'com.ly.cloud.logs.aop.WebLogAspect',
              line: { number: 125 },
              module: 'com.ly.cloud.logs.aop',
              function: 'doAround',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'AbstractAspectJAdvice.java',
              classname: 'org.springframework.aop.aspectj.AbstractAspectJAdvice',
              line: { number: 629 },
              module: 'org.springframework.aop.aspectj',
              function: 'invokeAdviceMethodWithGivenArgs',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AbstractAspectJAdvice.java',
              classname: 'org.springframework.aop.aspectj.AbstractAspectJAdvice',
              line: { number: 618 },
              function: 'invokeAdviceMethod',
              module: 'org.springframework.aop.aspectj',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AspectJAroundAdvice.java',
              classname: 'org.springframework.aop.aspectj.AspectJAroundAdvice',
              line: { number: 70 },
              module: 'org.springframework.aop.aspectj',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AfterReturningAdviceInterceptor.java',
              classname:
                'org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor',
              line: { number: 52 },
              module: 'org.springframework.aop.framework.adapter',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AspectJAfterThrowingAdvice.java',
              classname: 'org.springframework.aop.aspectj.AspectJAfterThrowingAdvice',
              line: { number: 62 },
              module: 'org.springframework.aop.aspectj',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ExposeInvocationInterceptor.java',
              classname: 'org.springframework.aop.interceptor.ExposeInvocationInterceptor',
              line: { number: 92 },
              module: 'org.springframework.aop.interceptor',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
          ],
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM ly_xtgl_yh',
          action: 'query',
          id: '44f8cf02d1d7dd73',
          type: 'db',
          db: {
            statement:
              "select distinct y.yhbh,y.yhmc,decode(y.xbm,1,'男',2,'女') xbm,b.bmmc,jg.JGMC,\n        ? as JSLX,? as JSBH,\n        y.DZYX,y.YDDH,y.YHLXBH,y.ZWMC\n    \tfrom ly_xtgl_yh y\n    \tleft join ly_xtgl_yh_js j on j.yhbh= y.yhbh\n    \tleft join ly_xtgl_bm_yh bmy on bmy.yhbh = y.yhbh and bmy.sfzy = '1'\n    \tleft join ly_xtgl_bm b on b.bmbh = bmy.bmbh\n        left join ly_xtgl_jg jg on y.JGBH = jg.JGBH\n    \twhere (y.jgbh = ? or ? = '-1') and y.scbs = '0'  and y.zt='1'\n    \t \n    \t\tand j.jsbh = ?\n    \t  \n    \t \n         \n         \n                 \n             \n    \t \n        \n        and exists (select 1 from LY_XTGL_JSB jsb where jsb.JSBH=?   and (jsb.JGBH = y.JGBH or (jsb.JGBH='-1' AND JSB.Jslx='1')))\n    \torder by y.yhbh",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.604Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        timestamp: { us: 1651045404604525 },
        span: {
          duration: { us: 24556 },
          stacktrace: [
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'DruidPooledPreparedStatement.java',
              classname: 'com.alibaba.druid.pool.DruidPooledPreparedStatement',
              line: { number: 243 },
              module: 'com.alibaba.druid.pool',
              function: 'executeQuery',
            },
            {
              exclude_from_grouping: false,
              library_frame: false,
              filename: 'MyPaginationInterceptor.java',
              classname: 'com.ly.cloud.common.mybatisplus.plugins.MyPaginationInterceptor',
              line: { number: 154 },
              module: 'com.ly.cloud.common.mybatisplus.plugins',
              function: 'queryTotal',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: 'MyPaginationInterceptor.java',
              classname: 'com.ly.cloud.common.mybatisplus.plugins.MyPaginationInterceptor',
              line: { number: 115 },
              module: 'com.ly.cloud.common.mybatisplus.plugins',
              function: 'intercept',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'Plugin.java',
              classname: 'org.apache.ibatis.plugin.Plugin',
              line: { number: 61 },
              function: 'invoke',
              module: 'org.apache.ibatis.plugin',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'SimpleExecutor.java',
              classname: 'org.apache.ibatis.executor.SimpleExecutor',
              line: { number: 85 },
              function: 'prepareStatement',
              module: 'org.apache.ibatis.executor',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'SimpleExecutor.java',
              classname: 'org.apache.ibatis.executor.SimpleExecutor',
              line: { number: 62 },
              module: 'org.apache.ibatis.executor',
              function: 'doQuery',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'BaseExecutor.java',
              classname: 'org.apache.ibatis.executor.BaseExecutor',
              line: { number: 326 },
              module: 'org.apache.ibatis.executor',
              function: 'queryFromDatabase',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'BaseExecutor.java',
              classname: 'org.apache.ibatis.executor.BaseExecutor',
              line: { number: 156 },
              module: 'org.apache.ibatis.executor',
              function: 'query',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'BaseExecutor.java',
              classname: 'org.apache.ibatis.executor.BaseExecutor',
              line: { number: 136 },
              module: 'org.apache.ibatis.executor',
              function: 'query',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'DefaultSqlSession.java',
              classname: 'org.apache.ibatis.session.defaults.DefaultSqlSession',
              line: { number: 148 },
              module: 'org.apache.ibatis.session.defaults',
              function: 'selectList',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'SqlSessionTemplate.java',
              classname: 'org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor',
              line: { number: 433 },
              module: 'org.mybatis.spring',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'SqlSessionTemplate.java',
              classname: 'org.mybatis.spring.SqlSessionTemplate',
              line: { number: 238 },
              module: 'org.mybatis.spring',
              function: 'selectList',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MapperMethod.java',
              classname: 'org.apache.ibatis.binding.MapperMethod',
              line: { number: 137 },
              module: 'org.apache.ibatis.binding',
              function: 'executeForMany',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MapperMethod.java',
              classname: 'org.apache.ibatis.binding.MapperMethod',
              line: { number: 76 },
              module: 'org.apache.ibatis.binding',
              function: 'execute',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MapperProxy.java',
              classname: 'org.apache.ibatis.binding.MapperProxy',
              line: { number: 59 },
              module: 'org.apache.ibatis.binding',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AopUtils.java',
              classname: 'org.springframework.aop.support.AopUtils',
              line: { number: 333 },
              module: 'org.springframework.aop.support',
              function: 'invokeJoinpointUsingReflection',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 190 },
              module: 'org.springframework.aop.framework',
              function: 'invokeJoinpoint',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 157 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'PersistenceExceptionTranslationInterceptor.java',
              classname:
                'org.springframework.dao.support.PersistenceExceptionTranslationInterceptor',
              line: { number: 136 },
              module: 'org.springframework.dao.support',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'JdkDynamicAopProxy.java',
              classname: 'org.springframework.aop.framework.JdkDynamicAopProxy',
              line: { number: 213 },
              module: 'org.springframework.aop.framework',
              function: 'invoke',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: 'UserClientServiceImpl.java',
              classname: 'com.ly.cloud.authc.service.impl.UserClientServiceImpl',
              line: { number: 293 },
              module: 'com.ly.cloud.authc.service.impl',
              function: 'getUsersByRoleId',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: '<generated>',
              classname:
                'com.ly.cloud.authc.service.impl.UserClientServiceImpl$$FastClassBySpringCGLIB$$7e5a448a',
              line: { number: -1 },
              module: 'com.ly.cloud.authc.service.impl',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MethodProxy.java',
              classname: 'org.springframework.cglib.proxy.MethodProxy',
              line: { number: 204 },
              module: 'org.springframework.cglib.proxy',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'CglibAopProxy.java',
              classname: 'org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation',
              line: { number: 738 },
              module: 'org.springframework.aop.framework',
              function: 'invokeJoinpoint',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 157 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'TransactionInterceptor.java',
              classname: 'org.springframework.transaction.interceptor.TransactionInterceptor$1',
              line: { number: 99 },
              module: 'org.springframework.transaction.interceptor',
              function: 'proceedWithInvocation',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'TransactionAspectSupport.java',
              classname: 'org.springframework.transaction.interceptor.TransactionAspectSupport',
              line: { number: 282 },
              module: 'org.springframework.transaction.interceptor',
              function: 'invokeWithinTransaction',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'TransactionInterceptor.java',
              classname: 'org.springframework.transaction.interceptor.TransactionInterceptor',
              line: { number: 96 },
              module: 'org.springframework.transaction.interceptor',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              function: 'proceed',
              module: 'org.springframework.aop.framework',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'CglibAopProxy.java',
              classname:
                'org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor',
              line: { number: 673 },
              module: 'org.springframework.aop.framework',
              function: 'intercept',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: '<generated>',
              classname:
                'com.ly.cloud.authc.service.impl.UserClientServiceImpl$$EnhancerBySpringCGLIB$$3bb30dca',
              line: { number: -1 },
              module: 'com.ly.cloud.authc.service.impl',
              function: 'getUsersByRoleId',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: 'UserClientController.java',
              classname: 'com.ly.cloud.authc.controller.UserClientController',
              line: { number: 331 },
              module: 'com.ly.cloud.authc.controller',
              function: 'getAllocationUsersByRoleId',
            },
            {
              exclude_from_grouping: false,
              library_frame: false,
              filename: '<generated>',
              classname:
                'com.ly.cloud.authc.controller.UserClientController$$FastClassBySpringCGLIB$$fc01b8e4',
              line: { number: -1 },
              module: 'com.ly.cloud.authc.controller',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MethodProxy.java',
              classname: 'org.springframework.cglib.proxy.MethodProxy',
              line: { number: 204 },
              module: 'org.springframework.cglib.proxy',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'CglibAopProxy.java',
              classname: 'org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation',
              line: { number: 738 },
              module: 'org.springframework.aop.framework',
              function: 'invokeJoinpoint',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 157 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'MethodBeforeAdviceInterceptor.java',
              classname: 'org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor',
              line: { number: 52 },
              module: 'org.springframework.aop.framework.adapter',
              function: 'invoke',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              exclude_from_grouping: false,
              library_frame: true,
              filename: 'MethodInvocationProceedingJoinPoint.java',
              classname: 'org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint',
              line: { number: 85 },
              module: 'org.springframework.aop.aspectj',
              function: 'proceed',
            },
            {
              library_frame: false,
              exclude_from_grouping: false,
              filename: 'WebLogAspect.java',
              classname: 'com.ly.cloud.logs.aop.WebLogAspect',
              line: { number: 125 },
              module: 'com.ly.cloud.logs.aop',
              function: 'doAround',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AbstractAspectJAdvice.java',
              classname: 'org.springframework.aop.aspectj.AbstractAspectJAdvice',
              line: { number: 629 },
              module: 'org.springframework.aop.aspectj',
              function: 'invokeAdviceMethodWithGivenArgs',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AbstractAspectJAdvice.java',
              classname: 'org.springframework.aop.aspectj.AbstractAspectJAdvice',
              line: { number: 618 },
              module: 'org.springframework.aop.aspectj',
              function: 'invokeAdviceMethod',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AspectJAroundAdvice.java',
              classname: 'org.springframework.aop.aspectj.AspectJAroundAdvice',
              line: { number: 70 },
              module: 'org.springframework.aop.aspectj',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AfterReturningAdviceInterceptor.java',
              classname:
                'org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor',
              line: { number: 52 },
              function: 'invoke',
              module: 'org.springframework.aop.framework.adapter',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'AspectJAfterThrowingAdvice.java',
              classname: 'org.springframework.aop.aspectj.AspectJAfterThrowingAdvice',
              line: { number: 62 },
              module: 'org.springframework.aop.aspectj',
              function: 'invoke',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ReflectiveMethodInvocation.java',
              classname: 'org.springframework.aop.framework.ReflectiveMethodInvocation',
              line: { number: 179 },
              module: 'org.springframework.aop.framework',
              function: 'proceed',
            },
            {
              library_frame: true,
              exclude_from_grouping: false,
              filename: 'ExposeInvocationInterceptor.java',
              classname: 'org.springframework.aop.interceptor.ExposeInvocationInterceptor',
              line: { number: 92 },
              module: 'org.springframework.aop.interceptor',
              function: 'invoke',
            },
          ],
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT',
          action: 'query',
          id: 'a5eaf0b63c60b948',
          type: 'db',
          db: {
            statement:
              "SELECT COUNT(1) FROM ( SELECT DISTINCT y.yhbh, y.yhmc, decode(y.xbm, 1, '男', 2, '女') xbm, b.bmmc, jg.JGMC, ? AS JSLX, ? AS JSBH, y.DZYX, y.YDDH, y.YHLXBH, y.ZWMC FROM ly_xtgl_yh y LEFT JOIN ly_xtgl_yh_js j ON j.yhbh = y.yhbh LEFT JOIN ly_xtgl_bm_yh bmy ON bmy.yhbh = y.yhbh AND bmy.sfzy = '1' LEFT JOIN ly_xtgl_bm b ON b.bmbh = bmy.bmbh LEFT JOIN ly_xtgl_jg jg ON y.JGBH = jg.JGBH WHERE (y.jgbh = ? OR ? = '-1') AND y.scbs = '0' AND y.zt = '1' AND j.jsbh = ? AND EXISTS (SELECT 1 FROM LY_XTGL_JSB jsb WHERE jsb.JSBH = ? AND (jsb.JGBH = y.JGBH OR (jsb.JGBH = '-1' AND JSB.Jslx = '1'))) ) TOTAL",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.600Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 1101 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_JSB',
          action: 'query',
          id: '7e43e7c480087510',
          type: 'db',
          db: {
            statement: 'select JSLX from LY_XTGL_JSB where JSBH = ?',
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404600366 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          type: 'apm-server',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.667Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 856 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_YH_YY',
          action: 'query',
          id: '157ce3c1bec6d66b',
          type: 'db',
          db: {
            statement:
              'select distinct yy.YYMC\n        from LY_XTGL_YH_YY  a left join LY_YYGL_YYB  yy on a.YYBH = yy.YYBH\n         \n              where 1 = 2',
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404667622 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.668Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 567 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_ER_BM',
          action: 'query',
          id: '0ec7b0b4fb23b5a0',
          type: 'db',
          db: {
            statement:
              'select distinct  b.BMMC\n        from LY_XTGL_ER_BM  a left join LY_XTGL_BM b on a.BMBH = b.BMBH\n         \n              where 1 = 2',
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404668796 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.675Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 515 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '32bf168025088c90',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404675623 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.676Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 505 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '4d6b851926ec7194',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404676435 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          type: 'apm-server',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.672Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 495 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '168a90df1ee45c06',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404672813 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.670Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        timestamp: { us: 1651045404670494 },
        span: {
          duration: { us: 468 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '9db7b77e00bfe652',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.674Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        timestamp: { us: 1651045404674324 },
        span: {
          duration: { us: 468 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '79c1f214751bff52',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.673Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        timestamp: { us: 1651045404673544 },
        span: {
          duration: { us: 463 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: 'def35a21d89b830e',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          type: 'apm-server',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.669Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 457 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '6f82a105f1f40174',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404669625 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.674Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        timestamp: { us: 1651045404674996 },
        span: {
          duration: { us: 423 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '487b4e6c06ab3e91',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.671Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        span: {
          duration: { us: 400 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: 'a2e1c91dd8ba28de',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
        timestamp: { us: 1651045404671297 },
      },
      {
        parent: { id: '7a236dfa6fc2509e' },
        agent: {
          name: 'java',
          ephemeral_id: 'b2f9f8f1-ce2e-4ed0-9d11-48b4545ca14d',
          version: '1.28.4',
        },
        destination: { address: '172.198.0.3', port: 1521, ip: '172.198.0.3' },
        processor: { name: 'transaction', event: 'span' },
        observer: {
          hostname: '6039561431b4',
          id: '4d64e0e3-8f61-4445-8eb7-1be73ef519f7',
          ephemeral_id: '00d990ad-a707-4544-9645-33e145d4c9bb',
          type: 'apm-server',
          version: '7.13.2',
          version_major: 7,
        },
        trace: { id: '8bf7c98bee7d10f8890cfb67d1ecf591' },
        '@timestamp': '2022-04-27T07:43:24.672Z',
        ecs: { version: '1.8.0' },
        service: { environment: 'production', name: 'LY-IACP-SVC' },
        event: { outcome: 'success' },
        transaction: { id: '7a236dfa6fc2509e' },
        timestamp: { us: 1651045404672011 },
        span: {
          duration: { us: 399 },
          subtype: 'oracle',
          destination: { service: { resource: 'oracle' } },
          name: 'SELECT FROM LY_XTGL_BM_YH',
          action: 'query',
          id: '897c0978898004b2',
          type: 'db',
          db: {
            statement:
              "SELECT  bm.bmmc\n            FROM LY_XTGL_BM_YH bmyh \n            LEFT JOIN LY_XTGL_BM bm ON bm.bmbh = bmyh.bmbh \n            where bmyh.yhbh = ? and bmyh.sfzy = '0'",
            type: 'sql',
            user: { name: 'LY_CLOUD_XTGL' },
          },
        },
      },
    ],
    exceedsMax: false,
    errorDocs: [],
  },
  errorsPerTransaction: {},
};

// 保留n位小数
function roundFun(value, n) {
  return Math.round(value * Math.pow(10, n)) / Math.pow(10, n);
}

// 单位转换
function unitChange(value) {
  if (value >= 10000) {
    return roundFun(value / 1000, 0) + ' ms';
  } else if (value < 10000 && value >= 1000) {
    return roundFun(value / 1000, 1) + ' ms';
  } else if (value < 1000) {
    return value + ' μs';
  }
}
let obj = {};
let parentIdList = [];
dataSource.trace.items.map(item => {
  if (item.container) {
    let {
      transaction: { name, duration, id },
      timestamp,
    } = item;
    let _item = { name, timestamp, duration, label: unitChange(duration.us) };
    obj[id] = [];
    obj[id].push(_item);
    // 记录id
    // parentIdList.push(transaction.id);
  }
  if (item.parent) {
    let {
      timestamp,
      span: { duration, name },
    } = item;
    let _item = { timestamp, duration, name, label: unitChange(duration.us) };
    obj[item.parent.id].push(_item);
  }
});

// 记录起始的时间戳
let firsttimestamp=obj['7a236dfa6fc2509e'][0].timestamp.us
let _dataSource=obj['7a236dfa6fc2509e'].sort(
  (a, b) => a.timestamp.us - b.timestamp.us
).map((item,index)=>{
    if(index==0) {
        item.timestamp=0
    }
    else item.timestamp=item.timestamp.us-firsttimestamp

    return item
})
